### ISSUE TITLE
Sass::SyntaxError while deploying to Heroku

### ISSUE THREAD

**Issue by ohaddahan** [camertron/mosaico-rails#5]
I'm getting the following error while pushing to Heroku.

>  I, [2019-02-07T22:10:23.851699 #1880]  INFO -- : Writing /tmp/build_aa4f93bfd0b22b364ffba96197532b1b/public/assets/mosaico/application-75117c1cdfbb9f079edecaa5afaa71262b3f96d8a042af4a510773c80f01ad1c.js.gz
>        rake aborted!
>        Sass::SyntaxError: Invalid CSS after "...ratio:0){@media": expected media query (e.g. print, screen, print and screen), was "{#main-wysiwyg-..."
>        (sass):5

I found the content is in files:

> ruby-2.6.0/gems/mosaico-1.0.0//vendor/assets/mosaico-0.16.0/mosaico/dist/mosaico.min.css
> ruby-2.6.0/gems/mosaico-1.0.0//vendor/assets/mosaico-0.16.0/mosaico/dist/mosaico-material.min.css

I tried running `Sass.compile_file` and `sass -C`, both are OK.
Any idea?

**Comment by ohaddahan** [comment]
Can also be replicated by:
`env SECRET_KEY_BASE=production_test_key  rake assets:precompile RAILS_ENV=production --trace `
@camertron

**Comment by camertron** [comment]
This was an interesting one to track down. It looks like the error happens because of this media query in the files you identified:

```css
@media {
  ...
}
```

According to the W3C's CSS validator, that's a valid media query. However, it looks like Sass doesn't like it. I'm not sure why `sass -c` works, but I can verify the problem goes away if we use the default `all` type in the media query:

```css
@media all {
  ...
}
```

I fixed the CSS manually and published a new version of the gem (v1.0.1). Run `bundle update mosaico` and then try deploying to Heroku again. Should be fixed :)

**Comment by ohaddahan** [comment]
Thanks @camertron , I know very little of CSS syntax so my expertise ended after trying the couple of commands specified here :)
